name: Sign ACR Images with Notary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v3
    - name: ACR build
      run: |
        az acr build --registry <registry-name> -t web-app-sample:${{ github.run_id }} .
    - uses: Duffney/setup-notation@v0.1.0
      name: Setup Notation CLI
      with:
        version: 0.9.0-alpha.1
        key_name: <key-name>
        certificate_key_id: <certificate-key-id>
        plugin_name: notation-azure-kv
        plugin_version: 0.3.1-alpha.1
    - uses: Duffney/notary-sign-action@v0.1.0
      name: Sign container image
      env:
        NOTATION_USERNAME: ${{ secrets.NOTATION_USERNAME }}
        NOTATION_PASSWORD: ${{ secrets.NOTATION_PASSWORD }}
      with:
        image-name: <registry-name>.azurecr.io/web-app-sample:${{ github.run_id }}